### ISSUE TITLE
[Feature/Request] Extends to append the information about changed file in the dispatching information

### ISSUE THREAD

**Issue by userlocalhost** [StackStorm-Exchange/stackstorm-bitbucket#11]
## Background
When a monitoring repository is updated, the sensor `RepositorySensor` dispatches the following information for each commit to the trigger `bitbucket.repository_event`, as described [here](https://github.com/StackStorm-Exchange/stackstorm-bitbucket#trigger-bitbucketrepository_event-trigger).

* Repository name which is updated by the commit
* Branch name which is updated by the commit
* Author who commits
* Committed time
* Commit message

## Problem
I want to make different Rules according to the changed file in a Repository.
But, I can't identify the changed file from the dispatched information in the current implementation.

## Proposal
Changing to append the information about changed file for each commit in the dispatching information.

**Comment by LindsayHill** [comment]
Sounds good. Will it cope with a variable number of changed files? Or maybe a high number of changed files?

**Comment by userlocalhost** [comment]
Thank you for your reply.

I think this requirement is trivial, so I want to implement it as small change as possible.
Of course, I also think that the backward compatibility should be assured in this change.

**Comment by LindsayHill** [comment]
Resolved by #12
