### ISSUE TITLE
The 'RepositorySensor' will crash when a new branch is created after it's started

### ISSUE THREAD

**Issue by userlocalhost** [StackStorm-Exchange/stackstorm-bitbucket#9]
In the [`get_{server|cloud}_updated_commits`](https://github.com/StackStorm-Exchange/stackstorm-bitbucket/blob/master/sensors/repository_sensor.py#L68) method which is called by `poll`, an exception of `KeyError` would be occurred when a new branch is created.

On the construction processing, 'RepositorySensor' checks last commits of all branches every repository.
After that, it monitors updated commits for them. But a new branch is appeared, a `KeyError` exception is raised.

I think it's reasonable solution to fix the branches to monitor in the configuration than applying the dynamically changing of branch in the repository.

Because there are many branches in the remote repository and most of them are temporary one. It's waste of resources to check update commit of them.

**Comment by LindsayHill** [comment]
Yes, I think you're right - better to just monitor a fixed set of branches. Maybe default to master if not specified?

**Comment by userlocalhost** [comment]
Thank you for your review.

> Maybe default to master if not specified?

I agree with you and I'll fix it soon.
